defmodule Goods.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:business_profiles) do
      add_if_not_exists :company_key, :text
    end

    drop_if_exists unique_index(:business_profiles, [:user_id],
                     name: "business_profiles_unique_business_profile_per_user_index"
                   )

    create unique_index(:business_profiles, [:company_key, :user_id],
             name: "business_profiles_unique_business_profile_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:business_profiles, [:company_key, :user_id],
                     name: "business_profiles_unique_business_profile_per_user_index"
                   )

    create unique_index(:business_profiles, [:user_id],
             name: "business_profiles_unique_business_profile_per_user_index"
           )

    alter table(:business_profiles) do
      remove_if_exists :company_key
    end
  end
end
