defmodule Goods.Repo.Migrations.MigrateResources12 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:parcel_bookings) do
      remove :sender_id
    end
  end

  def down do
    alter table(:parcel_bookings) do
      add :sender_id, :text, null: false
    end
  end
end
