defmodule Goods.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:parcel_bookings) do
      add_if_not_exists :parcel_number, :text
    end
  end

  def down do
    alter table(:parcel_bookings) do
      remove_if_exists :parcel_number
    end
  end
end
