defmodule Goods.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add_if_not_exists :company_key, :text
    end

    alter table(:parcel_bookings) do
      add_if_not_exists :company_key, :text
    end
  end

  def down do
    alter table(:parcel_bookings) do
      remove_if_exists :company_key
    end

    alter table(:users) do
      remove_if_exists :company_key
    end
  end
end
