defmodule Goods.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # No-op: business_profiles was already created by 20260324130000_add_business_profiles.exs
    :ok
  end

  def down do
    :ok
  end
end
