defmodule Goods.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:parcel_bookings) do
      remove :receiver_id
    end
  end

  def down do
    alter table(:parcel_bookings) do
      add :receiver_id, :text
    end
  end
end
