defmodule Goods.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:parcel_bookings) do
      add :origin_office_id, :text
      add :destination_office_id, :text
      add :route_id, :text
    end

    alter table(:business_profiles) do
      add :base_office, :text
      add :branch_offices, :text
      add :delivery_destinations, :text
      add :transfer_points, :text
      add :valid_routes, :text
    end
  end

  def down do
    alter table(:business_profiles) do
      remove :valid_routes
      remove :transfer_points
      remove :delivery_destinations
      remove :branch_offices
      remove :base_office
    end

    alter table(:parcel_bookings) do
      remove :route_id
      remove :destination_office_id
      remove :origin_office_id
    end
  end
end
