defmodule Goods.Repo.Migrations.AddParcelBookings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:parcel_bookings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sender_name, :text
      add :sender_phone, :text
      add :receiver_name, :text
      add :receiver_phone, :text
      add :destination, :text
      add :parcel_type, :text
      add :quantity, :bigint
      add :price, :decimal
    end
  end

  def down do
    drop table(:parcel_bookings)
  end
end
