defmodule Goods.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :hashed_password, :text, null: true
      add :name, :text
      add :role, :text, null: false, default: "client"
      add :invite_token, :text
      add :invite_sent_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :invite_sent_at
      remove :invite_token
      remove :role
      remove :name
      modify :hashed_password, :text, null: false
    end
  end
end
