defmodule Goods.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:parcel_bookings) do
      modify :price, :decimal, null: false
      modify :quantity, :bigint, null: false
      modify :parcel_type, :text, null: false
      modify :destination, :text, null: false
      modify :receiver_phone, :text, null: false
      modify :receiver_name, :text, null: false
      modify :sender_phone, :text, null: false
      modify :sender_id, :text, null: false
      modify :sender_name, :text, null: false
    end
  end

  def down do
    alter table(:parcel_bookings) do
      modify :sender_name, :text, null: true
      modify :sender_id, :text, null: true
      modify :sender_phone, :text, null: true
      modify :receiver_name, :text, null: true
      modify :receiver_phone, :text, null: true
      modify :destination, :text, null: true
      modify :parcel_type, :text, null: true
      modify :quantity, :bigint, null: true
      modify :price, :decimal, null: true
    end
  end
end
