defmodule Goods.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :approved_at
    end
  end

  def down do
    alter table(:users) do
      add :approved_at, :utc_datetime_usec
    end
  end
end
